"""Initial_db

Revision ID: 9a1cc5d8f12b
Revises: 77029703dd02
Create Date: 2022-06-02 12:24:12.587451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a1cc5d8f12b'
down_revision = '77029703dd02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crew', sa.Column('ship', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crew', 'ship')
    # ### end Alembic commands ###
